# Generated by Django 3.1.3 on 2020-12-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultpage', '0005_auto_20201201_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawimage',
            name='photo_url',
        ),
        migrations.AlterField(
            model_name='rawimage',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='raw_image'),
        ),
    ]
