# Generated by Django 3.1.3 on 2020-12-01 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultpage', '0006_auto_20201201_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawimage',
            old_name='image_file',
            new_name='photo',
        ),
        migrations.AddField(
            model_name='rawimage',
            name='url',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
