# Generated by Django 3.1.3 on 2020-12-01 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultpage', '0009_auto_20201201_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawimage',
            name='url',
        ),
    ]
