# Generated by Django 3.1.3 on 2020-12-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultpage', '0010_remove_rawimage_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawimage',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
