# Generated by Django 3.1.3 on 2020-12-01 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultpage', '0011_rawimage_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawimage',
            name='url',
        ),
    ]
