# Generated by Django 3.1.3 on 2020-12-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultpage', '0012_remove_rawimage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawimage',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='raw_image'),
        ),
    ]
