# Generated by Django 3.1.3 on 2020-12-02 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultpage', '0014_auto_20201202_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputimage',
            name='raw_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultpage.rawimage'),
        ),
        migrations.DeleteModel(
            name='ProcessedImage',
        ),
    ]
