# Generated by Django 3.1.3 on 2020-12-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultpage', '0018_auto_20201203_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawimage',
            name='brightness',
            field=models.IntegerField(default=0),
        ),
    ]
