# Generated by Django 3.1.3 on 2020-12-04 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resultpage', '0019_rawimage_brightness'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Result',
            new_name='Prediction',
        ),
        migrations.RemoveField(
            model_name='inputimage',
            name='raw_image',
        ),
    ]
