# Generated by Django 3.1.3 on 2020-12-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resultpage', '0020_auto_20201204_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='label',
            field=models.TextField(default='untitled'),
        ),
    ]
