# Generated by Django 3.1.3 on 2020-12-08 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resultpage', '0021_auto_20201204_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processedimage',
            name='raw_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resultpage.rawimage'),
        ),
    ]
